server:
    port: 8081
spring:
    application:
        name: backend
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    devtools:
        restart:
            enabled: true   #devtools로 변경을 감지함
        livereload:
            enabled: true   #실시간으로 새로고침을 허용
jwt:
    secret: ${JWT_SECRET}
    expiration-time: 86400000 # 1일간 저장
recaptcha:
  secret: ${RECAPTCHA_SECRET}
logging:
    level:
        org.springframework.security: DEBUG